services:
  devcontainer:    
    image: mcr.microsoft.com/devcontainers/base:jammy
    command: ["sleep", "infinity"]
    depends_on:
      - mongo  # Ensures MongoDB starts before devcontainer
    networks:
      - backend_network  # Uses a shared network
    environment:
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGODB_URI: mongodb://mongo:27017/todoapp  # Connect to MongoDB inside the network
      JWT_SECRET: $JWT_SECRET
      PORT: 3000
    ports:
      - "3000:3000"  # Exposes the app's port 3000 to the host
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh:/home/vscode/.ssh:cached

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"  # Exposes MongoDB to the host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - backend_network  # Uses the same network as devcontainer

networks:
  backend_network:  # Defines a custom network
    driver: bridge
